default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bob_bot_development

test:
  <<: *default
  database: bob_bot_test

production:
  <<: *default
  database: bob_bot_development
  username: bob_bot
  password: bob_bot
